"use client";

import { useCallback, useEffect, useState } from "react";

type Nudge = {
  id: string;
  kind: string;
  headline: string;
  detail: string;
  suggestedAction: string | null;
  priority: number;
  createdAt: string;
};

/**
 * Insights widget: surfaces proactive nudges generated by the weekly cron.
 * Shows at most 2 per 7-day window (enforced server-side). User can dismiss
 * or act on (which threads to chat).
 *
 * Placed above the chat thread so it's visible but not intrusive.
 */
export function NudgesWidget(props: {
  onActOnNudge?: (suggestion: string) => void;
}) {
  const [nudges, setNudges] = useState<Nudge[]>([]);
  const [loaded, setLoaded] = useState(false);

  const load = useCallback(async () => {
    try {
      const res = await fetch("/api/nudges", { cache: "no-store" });
      const body = (await res.json()) as {
        ok?: boolean;
        nudges?: Nudge[];
      };
      if (res.ok && body.ok) setNudges(body.nudges ?? []);
    } catch {
      /* silent — nudges are a nice-to-have */
    } finally {
      setLoaded(true);
    }
  }, []);

  useEffect(() => {
    void load();
  }, [load]);

  async function updateNudge(id: string, action: "dismiss" | "acted_on") {
    try {
      await fetch(`/api/nudges/${id}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ action })
      });
    } catch {
      /* silent */
    }
    setNudges((prev) => prev.filter((n) => n.id !== id));
  }

  if (!loaded || nudges.length === 0) return null;

  return (
    <section className="nudgesWidget">
      <div className="nudgesWidgetHeader">
        <p className="eyebrow">Insights</p>
        <h3>I noticed a couple of things this week.</h3>
      </div>
      <ul className="nudgesList">
        {nudges.map((n) => (
          <li key={n.id} className="nudgeItem">
            <div className="nudgeHeadline">{n.headline}</div>
            <div className="nudgeDetail">{n.detail}</div>
            <div className="nudgeActions">
              {n.suggestedAction && props.onActOnNudge ? (
                <button
                  type="button"
                  className="primaryButton"
                  onClick={() => {
                    props.onActOnNudge?.(n.suggestedAction ?? n.headline);
                    void updateNudge(n.id, "acted_on");
                  }}
                >
                  {n.suggestedAction}
                </button>
              ) : null}
              <button
                type="button"
                className="linkButton"
                onClick={() => updateNudge(n.id, "dismiss")}
              >
                Dismiss
              </button>
            </div>
          </li>
        ))}
      </ul>
    </section>
  );
}
